
// This code conforms with the UFC specification version 2018.2.0.dev0
// and was automatically generated by FFCx version 0.8.0.dev0.
//
// This code was generated with the following options:
//
//  {'epsilon': 1e-14,
//   'output_directory': '.',
//   'profile': False,
//   'scalar_type': 'float64',
//   'sum_factorization': False,
//   'table_atol': 1e-09,
//   'table_rtol': 1e-06,
//   'ufl_file': ['mwe_pure_ufl.py'],
//   'verbosity': 30,
//   'visualise': False}

#include <math.h>
#include <stdalign.h>
#include <stdlib.h>
#include <string.h>
#include <ufcx.h>

// Code for element element_712b97cf8c20314449c31b6faa0d429d0a020bc4

ufcx_finite_element element_712b97cf8c20314449c31b6faa0d429d0a020bc4 =
    {
        .signature = "Basix element (P, triangle, 1, gll_warped, unset, False, float64, [])",
        .cell_shape = triangle,
        .element_type = ufcx_basix_element,
        .topological_dimension = 2,
        .space_dimension = 3,
        .reference_value_rank = 0,
        .reference_value_shape = NULL,
        .reference_value_size = 1,
        .degree = 1,
        .block_size = 1,
        .basix_family = 1,
        .basix_cell = 2,
        .discontinuous = false,
        .lagrange_variant = 2,
        .dpc_variant = 0,
        .num_sub_elements = 0,
        .sub_elements = NULL,
        .custom_element = NULL,
        .custom_quadrature = NULL};

// End of code for element element_712b97cf8c20314449c31b6faa0d429d0a020bc4

// Code for element element_ab3ab6d636218a22f5f7b9a8dcf5e89b39b016c0

int reference_value_shape_element_ab3ab6d636218a22f5f7b9a8dcf5e89b39b016c0[1] = {2};
ufcx_finite_element *sub_elements_element_ab3ab6d636218a22f5f7b9a8dcf5e89b39b016c0[2] = {&element_712b97cf8c20314449c31b6faa0d429d0a020bc4, &element_712b97cf8c20314449c31b6faa0d429d0a020bc4};

ufcx_finite_element element_ab3ab6d636218a22f5f7b9a8dcf5e89b39b016c0 =
    {
        .signature = "blocked element (Basix element (P, triangle, 1, gll_warped, unset, False, float64, []), (2,))",
        .cell_shape = triangle,
        .element_type = ufcx_basix_element,
        .topological_dimension = 2,
        .space_dimension = 6,
        .reference_value_rank = 1,
        .reference_value_shape = reference_value_shape_element_ab3ab6d636218a22f5f7b9a8dcf5e89b39b016c0,
        .reference_value_size = 2,
        .degree = 1,
        .block_size = 2,
        .basix_family = 1,
        .basix_cell = 2,
        .discontinuous = false,
        .lagrange_variant = 2,
        .dpc_variant = 0,
        .num_sub_elements = 2,
        .sub_elements = sub_elements_element_ab3ab6d636218a22f5f7b9a8dcf5e89b39b016c0,
        .custom_element = NULL,
        .custom_quadrature = NULL};

// End of code for element element_ab3ab6d636218a22f5f7b9a8dcf5e89b39b016c0

// Code for element element_f99c97188ff012ce840dfb7e251cf41c8f652cf6

ufcx_finite_element element_f99c97188ff012ce840dfb7e251cf41c8f652cf6 =
    {
        .signature = "Basix element (P, triangle, 2, gll_warped, unset, False, float64, [])",
        .cell_shape = triangle,
        .element_type = ufcx_basix_element,
        .topological_dimension = 2,
        .space_dimension = 6,
        .reference_value_rank = 0,
        .reference_value_shape = NULL,
        .reference_value_size = 1,
        .degree = 2,
        .block_size = 1,
        .basix_family = 1,
        .basix_cell = 2,
        .discontinuous = false,
        .lagrange_variant = 2,
        .dpc_variant = 0,
        .num_sub_elements = 0,
        .sub_elements = NULL,
        .custom_element = NULL,
        .custom_quadrature = NULL};

// End of code for element element_f99c97188ff012ce840dfb7e251cf41c8f652cf6

// Code for dofmap dofmap_712b97cf8c20314449c31b6faa0d429d0a020bc4

int entity_dofs_dofmap_712b97cf8c20314449c31b6faa0d429d0a020bc4[3] = {0, 1, 2};

int entity_dof_offsets_dofmap_712b97cf8c20314449c31b6faa0d429d0a020bc4[8] = {0, 1, 2, 3, 3, 3, 3, 3};

int entity_closure_dofs_dofmap_712b97cf8c20314449c31b6faa0d429d0a020bc4[12] = {0, 1, 2, 1, 2, 0, 2, 0, 1, 0, 1, 2};

int entity_closure_dof_offsets_dofmap_712b97cf8c20314449c31b6faa0d429d0a020bc4[8] = {0, 1, 2, 3, 5, 7, 9, 12};

ufcx_dofmap dofmap_712b97cf8c20314449c31b6faa0d429d0a020bc4 =
    {
        .signature = "FFCx dofmap for Basix element (P, triangle, 1, gll_warped, unset, False, float64, [])",
        .num_global_support_dofs = 0,
        .num_element_support_dofs = 3,
        .block_size = 1,
        .entity_dofs = entity_dofs_dofmap_712b97cf8c20314449c31b6faa0d429d0a020bc4,
        .entity_dof_offsets = entity_dof_offsets_dofmap_712b97cf8c20314449c31b6faa0d429d0a020bc4,
        .entity_closure_dofs = entity_closure_dofs_dofmap_712b97cf8c20314449c31b6faa0d429d0a020bc4,
        .entity_closure_dof_offsets = entity_closure_dof_offsets_dofmap_712b97cf8c20314449c31b6faa0d429d0a020bc4,
        .num_sub_dofmaps = 0,
        .sub_dofmaps = NULL};

// End of code for dofmap dofmap_712b97cf8c20314449c31b6faa0d429d0a020bc4

// Code for dofmap dofmap_ab3ab6d636218a22f5f7b9a8dcf5e89b39b016c0

ufcx_dofmap *sub_dofmaps_dofmap_ab3ab6d636218a22f5f7b9a8dcf5e89b39b016c0[2] = {&dofmap_712b97cf8c20314449c31b6faa0d429d0a020bc4, &dofmap_712b97cf8c20314449c31b6faa0d429d0a020bc4};

int entity_dofs_dofmap_ab3ab6d636218a22f5f7b9a8dcf5e89b39b016c0[3] = {0, 1, 2};

int entity_dof_offsets_dofmap_ab3ab6d636218a22f5f7b9a8dcf5e89b39b016c0[8] = {0, 1, 2, 3, 3, 3, 3, 3};

int entity_closure_dofs_dofmap_ab3ab6d636218a22f5f7b9a8dcf5e89b39b016c0[12] = {0, 1, 2, 1, 2, 0, 2, 0, 1, 0, 1, 2};

int entity_closure_dof_offsets_dofmap_ab3ab6d636218a22f5f7b9a8dcf5e89b39b016c0[8] = {0, 1, 2, 3, 5, 7, 9, 12};

ufcx_dofmap dofmap_ab3ab6d636218a22f5f7b9a8dcf5e89b39b016c0 =
    {
        .signature = "FFCx dofmap for blocked element (Basix element (P, triangle, 1, gll_warped, unset, False, float64, []), (2,))",
        .num_global_support_dofs = 0,
        .num_element_support_dofs = 3,
        .block_size = 2,
        .entity_dofs = entity_dofs_dofmap_ab3ab6d636218a22f5f7b9a8dcf5e89b39b016c0,
        .entity_dof_offsets = entity_dof_offsets_dofmap_ab3ab6d636218a22f5f7b9a8dcf5e89b39b016c0,
        .entity_closure_dofs = entity_closure_dofs_dofmap_ab3ab6d636218a22f5f7b9a8dcf5e89b39b016c0,
        .entity_closure_dof_offsets = entity_closure_dof_offsets_dofmap_ab3ab6d636218a22f5f7b9a8dcf5e89b39b016c0,
        .num_sub_dofmaps = 2,
        .sub_dofmaps = sub_dofmaps_dofmap_ab3ab6d636218a22f5f7b9a8dcf5e89b39b016c0};

// End of code for dofmap dofmap_ab3ab6d636218a22f5f7b9a8dcf5e89b39b016c0

// Code for dofmap dofmap_f99c97188ff012ce840dfb7e251cf41c8f652cf6

int entity_dofs_dofmap_f99c97188ff012ce840dfb7e251cf41c8f652cf6[6] = {0, 1, 2, 3, 4, 5};

int entity_dof_offsets_dofmap_f99c97188ff012ce840dfb7e251cf41c8f652cf6[8] = {0, 1, 2, 3, 4, 5, 6, 6};

int entity_closure_dofs_dofmap_f99c97188ff012ce840dfb7e251cf41c8f652cf6[18] = {0, 1, 2, 1, 2, 3, 0, 2, 4, 0, 1, 5, 0, 1, 2, 3, 4, 5};

int entity_closure_dof_offsets_dofmap_f99c97188ff012ce840dfb7e251cf41c8f652cf6[8] = {0, 1, 2, 3, 6, 9, 12, 18};

ufcx_dofmap dofmap_f99c97188ff012ce840dfb7e251cf41c8f652cf6 =
    {
        .signature = "FFCx dofmap for Basix element (P, triangle, 2, gll_warped, unset, False, float64, [])",
        .num_global_support_dofs = 0,
        .num_element_support_dofs = 6,
        .block_size = 1,
        .entity_dofs = entity_dofs_dofmap_f99c97188ff012ce840dfb7e251cf41c8f652cf6,
        .entity_dof_offsets = entity_dof_offsets_dofmap_f99c97188ff012ce840dfb7e251cf41c8f652cf6,
        .entity_closure_dofs = entity_closure_dofs_dofmap_f99c97188ff012ce840dfb7e251cf41c8f652cf6,
        .entity_closure_dof_offsets = entity_closure_dof_offsets_dofmap_f99c97188ff012ce840dfb7e251cf41c8f652cf6,
        .num_sub_dofmaps = 0,
        .sub_dofmaps = NULL};

// End of code for dofmap dofmap_f99c97188ff012ce840dfb7e251cf41c8f652cf6

// Code for integral integral_a80de02e2fc39315d8672b75da91b1586209cb47

void tabulate_tensor_integral_a80de02e2fc39315d8672b75da91b1586209cb47(double *restrict A,
                                                                       const double *restrict w,
                                                                       const double *restrict c,
                                                                       const double *restrict coordinate_dofs,
                                                                       const int *restrict entity_local_index,
                                                                       const uint8_t *restrict quadrature_permutation)
{
  // Quadrature rules
  static const double weights_39d[6] = {0.054975871827661, 0.054975871827661, 0.054975871827661, 0.1116907948390055, 0.1116907948390055, 0.1116907948390055};
  // Precomputed values of basis functions and precomputations
  // FE* dimensions: [permutation][entities][points][dofs]
  static const double FE1_C0_D10_Q39d[1][1][1][3] = {{{{-1.0, 1.0, 0.0}}}};
  static const double FE1_C1_D01_Q39d[1][1][1][3] = {{{{-1.0, 0.0, 1.0}}}};
  static const double FE2_C0_Q39d[1][1][6][6] = {{{{-0.07480380774819603, 0.5176323419876736, -0.07480380774819671, 0.2992152309927871, 0.03354481152314834, 0.2992152309927839},
                                                   {-0.07480380774819613, -0.0748038077481966, 0.5176323419876735, 0.2992152309927871, 0.2992152309927838, 0.03354481152314828},
                                                   {0.5176323419876713, -0.0748038077481967, -0.07480380774819674, 0.03354481152314866, 0.2992152309927869, 0.2992152309927868},
                                                   {-0.04820837781551195, -0.08473049309397784, -0.04820837781551192, 0.1928335112620479, 0.7954802262009061, 0.1928335112620478},
                                                   {-0.04820837781551193, -0.048208377815512, -0.08473049309397786, 0.1928335112620479, 0.192833511262048, 0.7954802262009062},
                                                   {-0.08473049309397794, -0.04820837781551188, -0.04820837781551195, 0.7954802262009061, 0.1928335112620479, 0.1928335112620479}}}};
  // ------------------------
  // Section: Jacobian
  // Inputs: coordinate_dofs, FE1_C1_D01_Q39d, FE1_C0_D10_Q39d
  // Outputs: J_c3, J_c1, J_c2, J_c0
  double J_c0 = 0.0;
  double J_c3 = 0.0;
  double J_c1 = 0.0;
  double J_c2 = 0.0;
  {
    for (int ic = 0; ic < 3; ++ic)
    {
      J_c0 += coordinate_dofs[(ic) * 3] * FE1_C0_D10_Q39d[0][0][0][ic];
      J_c3 += coordinate_dofs[(ic) * 3 + 1] * FE1_C1_D01_Q39d[0][0][0][ic];
      J_c1 += coordinate_dofs[(ic) * 3] * FE1_C1_D01_Q39d[0][0][0][ic];
      J_c2 += coordinate_dofs[(ic) * 3 + 1] * FE1_C0_D10_Q39d[0][0][0][ic];
    }
  }
  // ------------------------
  double sp_39d_0 = J_c0 * J_c3;
  double sp_39d_1 = J_c1 * J_c2;
  double sp_39d_2 = -sp_39d_1;
  double sp_39d_3 = sp_39d_0 + sp_39d_2;
  double sp_39d_4 = fabs(sp_39d_3);
  for (int iq = 0; iq < 6; ++iq)
  {
    // Section: Intermediates
    double fw0 = 0;
    {
      fw0 = sp_39d_4 * weights_39d[iq];
    }
    // Section: Tensor Computation
    // Inputs: FE2_C0_Q39d, fw0
    // Outputs: A
    {
      double temp_0[6] = {0};
      for (int j = 0; j < 6; ++j)
      {
        temp_0[j] = fw0 * FE2_C0_Q39d[0][0][iq][j];
      }
      for (int j = 0; j < 6; ++j)
      {
        for (int i = 0; i < 6; ++i)
        {
          A[6 * (i) + (j)] += FE2_C0_Q39d[0][0][iq][i] * temp_0[j];
        }
      }
    }
  }
}

ufcx_integral integral_a80de02e2fc39315d8672b75da91b1586209cb47 =
    {
        .enabled_coefficients = NULL,
        .tabulate_tensor_float32 = NULL,
        .tabulate_tensor_float64 = tabulate_tensor_integral_a80de02e2fc39315d8672b75da91b1586209cb47,
        .tabulate_tensor_complex64 = NULL,
        .tabulate_tensor_complex128 = NULL,
        .needs_facet_permutations = false,
        .coordinate_element = &element_ab3ab6d636218a22f5f7b9a8dcf5e89b39b016c0,
};

// End of code for integral integral_a80de02e2fc39315d8672b75da91b1586209cb47

// Code for form form_598da04c64d41a43354e41ad7dd3f9021354d1f9

ufcx_dofmap *dofmaps_form_598da04c64d41a43354e41ad7dd3f9021354d1f9[2] = {&dofmap_f99c97188ff012ce840dfb7e251cf41c8f652cf6, &dofmap_f99c97188ff012ce840dfb7e251cf41c8f652cf6};
ufcx_finite_element *finite_elements_form_598da04c64d41a43354e41ad7dd3f9021354d1f9[2] = {&element_f99c97188ff012ce840dfb7e251cf41c8f652cf6, &element_f99c97188ff012ce840dfb7e251cf41c8f652cf6};
int form_integral_offsets_form_598da04c64d41a43354e41ad7dd3f9021354d1f9[4] = {0, 1, 1, 1};
static ufcx_integral *form_integrals_form_598da04c64d41a43354e41ad7dd3f9021354d1f9[1] = {&integral_a80de02e2fc39315d8672b75da91b1586209cb47};
int form_integral_ids_form_598da04c64d41a43354e41ad7dd3f9021354d1f9[1] = {-1};

ufcx_form form_598da04c64d41a43354e41ad7dd3f9021354d1f9 =
    {

        .signature = "47dc925f221ceaf1ee1bcd2a2bdaebe8efc487767f700d2634110137b15d231b49f716453c7b7450061192df950e08b23e85e725da222947664558ebab2e9588",
        .rank = 2,
        .num_coefficients = 0,
        .num_constants = 0,
        .original_coefficient_position = NULL,

        .coefficient_name_map = NULL,
        .constant_name_map = NULL,

        .finite_elements = finite_elements_form_598da04c64d41a43354e41ad7dd3f9021354d1f9,
        .dofmaps = dofmaps_form_598da04c64d41a43354e41ad7dd3f9021354d1f9,

        .form_integrals = form_integrals_form_598da04c64d41a43354e41ad7dd3f9021354d1f9,
        .form_integral_ids = form_integral_ids_form_598da04c64d41a43354e41ad7dd3f9021354d1f9,
        .form_integral_offsets = form_integral_offsets_form_598da04c64d41a43354e41ad7dd3f9021354d1f9};

// Alias name
ufcx_form *form_mwe_pure_ufl_a = &form_598da04c64d41a43354e41ad7dd3f9021354d1f9;

ufcx_function_space *functionspace_form_mwe_pure_ufl_a(const char *function_name)
{
  static ufcx_function_space functionspace_v =
      {
          .finite_element = &element_f99c97188ff012ce840dfb7e251cf41c8f652cf6,
          .dofmap = &dofmap_f99c97188ff012ce840dfb7e251cf41c8f652cf6,
          .geometry_family = "P",
          .geometry_degree = 1,
          .geometry_basix_cell = 2,
          .geometry_basix_variant = 2,
          .value_rank = 0,
          .value_shape = NULL};
  static ufcx_function_space functionspace_u =
      {
          .finite_element = &element_f99c97188ff012ce840dfb7e251cf41c8f652cf6,
          .dofmap = &dofmap_f99c97188ff012ce840dfb7e251cf41c8f652cf6,
          .geometry_family = "P",
          .geometry_degree = 1,
          .geometry_basix_cell = 2,
          .geometry_basix_variant = 2,
          .value_rank = 0,
          .value_shape = NULL};
  if (strcmp(function_name, "v") == 0)
    return &functionspace_v;
  if (strcmp(function_name, "u") == 0)
    return &functionspace_u;
  return NULL;
}

// End of code for form form_598da04c64d41a43354e41ad7dd3f9021354d1f9
